/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

 --1: Find total customers by countries
 select country ,
 COUNT(customer_key) AS total_customers
 from gold.dim_customers
 GROUP BY country
 ORDER BY total_customers DESC;

 --2: Find total customers by gender
 Select gender,
 COUNT(customer_key) AS total_genders
 from gold.dim_customers
 GROUP BY gender
 ORDER BY total_genders DESC;

 --3: Find total products by category
 select category,
 COUNT(product_key) AS total_products
 from gold.dim_products
 GROUP BY category
 ORDER BY total_products DESC;

 --4: What is the average costs in each category?
 select category,
 COUNT(cost) AS avg_cost
 from gold.dim_products
 GROUP BY category
 ORDER BY avg_cost DESC

 --5: What is the total revenue generated for each category?
 select 
 p.category,
 SUM(f.sales_amount) total_revenue
 from gold.fact_sales f
 LEFT JOIN gold.dim_products p
 ON p.product_key = f.product_key
 GROUP BY p.category
 ORDER BY total_revenue DESC;

 --6: What is the total revenue generated by each customer?
 Select 
 c.customer_key,
 c.first_name,
 c.last_name,
 SUM(f.sales_amount) total_revenue 
 From gold.fact_sales f
 LEFT JOIN gold.dim_customers c
 ON c.customer_key = f.customer_key
 GROUP BY c.customer_key,
 c.first_name,
 c.last_name
 ORDER BY total_revenue DESC;

 --7: What is the distribution of sold items across countries?
 Select 
 c.country,
 SUM(f.quantity) total_sold_items
 From gold.fact_sales f
 LEFT JOIN gold.dim_customers c
 ON c.customer_key = f.customer_key
 GROUP BY c.country
 ORDER BY  total_sold_items DESC;
